config/routes.rb
Rails.application.routes.draw do
  get "/" => 'sessions#index'

  get '/critics/partial' => 'critics#partial'
  resources :critics, except: [:new]

  post '/invitations/new' => 'invitations#new'
  delete '/invitations/:id' => 'invitations#delete'
  get '/invitations/:id' => 'invitations#redeem'
  get '/events/:event_id/invite' => 'reviews#create'
  resources :events, except: :index
  resources :movies
  get '/reviews/new/:event_id' => 'reviews#new'
  resources :reviews
  post '/reviews/:id/draftsave' => 'reviews#draftsave'
  post '/reviews/invite_handler' => 'reviews#invite_handler'   #not restful. sorry

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, class_name: "Critic"
  belongs_to :movie
  has_many :reviews
  has_many :critics, through: :reviews
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
    if @event.creator_id == session[:user_id] && @event.pub_date > Date.today
      render "events/edit"
    else
      redirect_to @event
    end
  end

  def create
    @event = Event.new(event_params)
    @event.creator = current_user
    if @event.save
      redirect_to @event
    else
      render "events/new"
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      redirect_to @event
    else
      render 'events/edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to '/'
  end

  private
    def event_params
      params.require(:event).permit(:pub_date, :name, :movie_id)
    end

end

app/helpers/events_helper.rb
module EventsHelper
  def event_is_editable?(event)
    return true if event && event.pub_date > Date.today
    return false
  end

  def event_is_publishible?(event)
    return true if event && event.pub_date <= Date.today
    return false
  end
end

app/views/events/_form.html.erb
<div class="main form">
  <h1>EVENT FORM</h1>
  <%= form_for @event do |f| %>
    <% if @event.errors.any? %>
      <% @event.errors.full_messages.each do |error| %>
        <div class = "error"><%= error %>!</div>
      <% end %>
    <% end %>
  <div class = "movie-selector">SELECT A MOVIE:
  <%= collection_select(:event, :movie_id, Movie.all, :id, :name, prompt: true) %>
  </div>
  <p>OR</p>
  <%=link_to "REGISTER NEW MOVIE", {controller: "movies", action: "new"}, class: "aButton"%>
  <div class = "pub-date">
    PUBLISHING DATE:
    <%= f.date_field :pub_date %>
  </div>
  <div class = "event-name">
    <%= f.text_field :name, :placeholder => 'EVENT NAME' %>
  </div>

    <%= f.submit %>

  <% end %>
</div>

app/views/events/edit.html.erb
<div class="new-event-container">
  <%= render 'events/form' %>
</div>

app/views/events/new.html.erb
<div class="new-event-container">
  <%= render 'events/form' %>
</div>

app/views/events/show.html.erb
<div class="main">
  <h2><%= @event.name %></h2>
  <h3 class="gray">REVIEWING</h3>
  <h1><%= @event.movie.name %></h1>
  <% if @event.pub_date > Date.today %>
    <p><%=time_ago_in_words(@event.pub_date).upcase %> LEFT TO CONTRIBUTE</p>
  <% else %>
    <p>EVENT CLOSED</p>
  <% end %>
  <div class="border"></div>
  <div class ="movie-img">
    <img src=<%=@event.movie.movie_image.url%>>
  </div>

  <div class="event-review-container">
    <p class="gray">REVIEWS FOR THIS EVENT:</p>
    <% if @event.pub_date > Date.today %>
      <% if @event.creator_id == session[:user_id] && event_is_editable?(@event) %>
        <button class="aButton" onclick="location.href='/events/<%= @event.id %>/invite';" id="make_invite">SELECT REVIEWERS</button>
        <%=link_to "EDIT EVENT", edit_event_path(@event.id), :class => 'aButton'%>
        <%=link_to "DELETE EVENT", event_path(@event.id), :method => :delete, :class => "delete aButton", :confirm => "Are you sure ?"%>
      <% end %>
    <% end %>
      <% @event.reviews.each do |review| %>
        <% if review.content != "" %>
        <div class="event-review" style="background-image: url(<%= review.critic.profile_image %>)">
          <h1><%= link_to review.critic.username, review %></h1>
            <% if review_has_data(review) %>
              <p>STARTED OR COMPLETED</p>
            <% end %>
          <% if review.critic.id == current_user.id && is_editable?(review)%>
            <p><a href="/reviews/<%=@event.reviews.find_by(critic_id: session[:user_id]).id%>/edit"> (Create / Edit your review) </a></p>
          <% end %>
        </div>
        <% end %>
      <% end %>
  </div>
</div>